[package]
name = "movecraft"
version = "0.0.1"


[addresses]
StarcoinFramework = "0x1"
StarcoinAssociation = "0xA550C18"
VMReserved = "0x0"
MoveCraft = "0xDEF"

[dev-dependencies]

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin.git", subdir="vm/stdlib", rev="3e895169a8f8dd883277050bb90645c52a370cee"}